BEGIN;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
  ID SERIAL PRIMARY KEY,
  USERNAME TEXT,
  EMAIL TEXT,
  PASSWORD TEXT
);

INSERT INTO USERS(USERNAME,EMAIL,PASSWORD) VALUES ('Ahmed','ahmed@gmail.com','123sele');

COMMIT;
